### ISSUE TITLE
repo not working

### ISSUE THREAD

**Issue by jalsco** [Hoangdus/Speedster#1]
Hey 😊
thanks for nice software ! But am having some trouble to install via a repo.

the repo :  `https://hoangdus.github.io/Tweaks/` 

doesn't add properly. Has address been updated ? 

I am using Sileo on an iOS 15.4.1 rootless jb with Dopamine, and hope to add Speedster tweak. The source adds, with errors, then shows with empty contents. As a  test I tried add the source to an iOS 14.3 ( jb by uncover), it also gives an error message.  

 
![image](https://github.com/Hoangdus/Speedster/assets/7985459/68e7fe0c-b9b8-44a3-b6ab-b5e3da66b635)

**Comment by jalsco** [comment]
Also - installing the rootless deb direct from the Releases - `https://github.com/Hoangdus/Speedster/releases`   results in SAFE MODE ..

**Comment by Hoangdus** [comment]
Hello, the repo is currently not updated for rootless jailbreak as I'm planning to move this tweak to a more mainstream repo. About the safemode issue can you send me a crash log and your tweak list? Thanks in advance

**Comment by Hoangdus** [comment]
> Also - installing the rootless deb direct from the Releases - `https://github.com/Hoangdus/Speedster/releases` results in SAFE MODE ..

Hello, the repo is currently not updated for rootless jailbreak as I'm planning to move this tweak to a more mainstream repo. About the safemode issue can you send me a crash log and your tweak list? Thanks in advance

**Comment by jalsco** [comment]
Sure -  crash log is where ? 
Only have a few other tweaks installed - 
```
FiveIconDock - Rootless
NetSpeed
Picarize
BioProtect  (rootless) 12-16
```

**Comment by Hoangdus** [comment]
> Sure -  crash log is where ? 
> 
> Only have a few other tweaks installed - 
> 
> ```
> 
> FiveIconDock - Rootless
> 
> NetSpeed
> 
> Picarize
> 
> BioProtect  (rootless) 12-16
> 
> ```
> 
> 

Sorry for the late reply. I can't seem to find a crash logger compatible with rootless jailbreak. But base on your tweak list I did some testing and it seems like bioprotect is the issue. I tried uninstalling every tweak on my test device and only install bioprotect and it crashed to safemode.

**Comment by jalsco** [comment]
Ok thank you  I will uninstall BioProtect

**Comment by Hoangdus** [comment]
> Ok thank you I will uninstall BioProtect

Oh you don't have to do that anymore, I found out the problem and working on a fix rn. Sorry for the confusion

**Comment by jalsco** [comment]
Its cool - I just noticed that you updated it 10-15 mins ago. I also confirmed here that the crash still happening with - netspeed, 5icondock and bioprotect all uninstalled.  

I will probably not reinstall Netspeed.  

I have not yet installed the most recent update to Speedster that u just made. Will do that shortly.  Thanks so much 🙏🏻

**Comment by jalsco** [comment]
which I should use for 12 pro max ? -- you have `arm` and also `arm64`. I am assuming `arm64` is right for me .

**Comment by jalsco** [comment]
Yes - that has fixed the problem. And Speedster is running great 😊 
I will buy u a fanta 😉
Bounce is too crazy - So I leave those settings off.  I use settings as below. 
For a few years was using AnimPlus on 14.3 (jb by uncover) - so was very difficult to go back to a slow UI. But Speedster now does same job !

TY so much ! ❤ -- there's a few other simple little Tweaks (where source code is on github) that need to be re-written for rootless. But their dev is no longer active.  A couple of my favs are: `CopyPasta` and `DontSwipe`  

https://www.idownloadblog.com/2021/02/01/copypasta-2/
https://github.com/liberatoaguilar/DontSwipe
https://github.com/LittenArchive/Copypasta

Thanks again 😊🙏🏻

![image](https://github.com/Hoangdus/Speedster/assets/7985459/994c8c6f-2412-4c2d-b52e-96a9136b4fcb)

**Comment by jalsco** [comment]
Possibly concern with Speedster is: **opening of Folder containing icons.** 
That seems still slow. Also is jerky and not smooth.  But if there is some way to add that as an option to also speed up that , inside the Speedster tweak, that would be great

**Comment by Hoangdus** [comment]
> Possibly concern with Speedster is: **opening of Folder containing icons.** 
> 
> That seems still slow. Also is jerky and not smooth.  But if there is some way to add that as an option to also speed up that , inside the Speedster tweak, that would be great 

Hmmm I might add in a future update

**Comment by Hoangdus** [comment]
> Yes - that has fixed the problem. And Speedster is running great 😊 
> 
> I will buy u a fanta 😉
> 
> Bounce is too crazy - So I leave those settings off.  I use settings as below. 
> 
> For a few years was using AnimPlus on 14.3 (jb by uncover) - so was very difficult to go back to a slow UI. But Speedster now does same job !
> 
> 
> 
> TY so much ! ❤ -- there's a few other simple little Tweaks (where source code is on github) that need to be re-written for rootless. But their dev is no longer active.  A couple of my favs are: `CopyPasta` and `DontSwipe`  
> 
> 
> 
> https://www.idownloadblog.com/2021/02/01/copypasta-2/
> 
> https://github.com/liberatoaguilar/DontSwipe
> 
> https://github.com/LittenArchive/Copypasta
> 
> 
> 
> Thanks again 😊🙏🏻
> 
> 
> 
> ![image](https://github.com/Hoangdus/Speedster/assets/7985459/994c8c6f-2412-4c2d-b52e-96a9136b4fcb)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
>  

Glad to hear that, I hope you enjoy it

**Comment by jalsco** [comment]
Probably don't need CopyPasta as there's an alternative ( CopyLog tweak ).   Even though I find CopyPasta to have a much better interface - less intrusive - easier - and can see everything much more quickly. Reminds me of Ditto for windows. 

But if you are interested in renewing DontSwipe for rootless... that would be so awesome @  

https://github.com/liberatoaguilar/DontSwipe  😉
