### ISSUE TITLE
Instant safe mode upon installation

### ISSUE THREAD

**Issue by dhry** [Hoangdus/Speedster#2]
iOS 15.4.1, Dopam1ne, 13 pro.

**Comment by dhry** [comment]
Didn’t see 1.1.1 released on sileo.

**Comment by jalsco** [comment]
Issue is already fixed I believe. Get 1.1.1 from here :

 https://github.com/Hoangdus/Speedster/releases 

Click that link - and then find the 1.1.1 release and  "open in Sileo".

**Comment by Hoangdus** [comment]
> Didn’t see 1.1.1 released on sileo.

I just pushed the fix an hour or 2 ago to havoc it should be live now :D
