### ISSUE TITLE
Speedster needs update for Roothide compatability 

### ISSUE THREAD

**Issue by jalsco** [Hoangdus/Speedster#3]
Hi Hoang 😊

Can you please make update as below 👇
I did not want to run the Patcher tool against your code. IT is a very simple update, but better if you do it.
Pleasee 🙏🏻  

![File (3)](https://github.com/Hoangdus/Speedster/assets/7985459/f5be8d2c-edb6-469c-8896-38393dbceb6e)

**Comment by Hoangdus** [comment]
Hey, sorry for the extremely late reply, was busy with mid term over the past few weeks. About the roothide support, please just use the patcher as my tweak will work and behave the same as native roothide.
