### ISSUE TITLE
No Folder Open or Close speed? 

### ISSUE THREAD

**Issue by Oxtie** [Hoangdus/Speedster#4]
Why No Folder Open or Close speed supported?

And yes,.. For sake of safety, please update for arm64e devices (roothide) 😅

**Comment by jalsco** [comment]
Yes please -- folder open speed... 

Also begging +1 for Roothide 🙏🏻

**Comment by Hoangdus** [comment]
The folder speed issue is fixed in the latest release. About roothide support however, I'm afraid that is more complicated than you think. Please just use the patcher.

**Comment by Oxtie** [comment]
OK, for folders there is little speed (that too with animation stuttering) but no Bouncy animation like opening apps (which is what I want the most for folders) 🤔

**Comment by jalsco** [comment]
Thanks @Hoangdus  . 
As long as you confirm that the Patcher works and has no problems.  I will use it for RootHide

**Comment by Oxtie** [comment]
So,.. I guess bouncy animation is not possible on folders 🤔

**Comment by Hoangdus** [comment]
@Oxtie hey, sorry for the extremely late reply. Bouncy animation is possible but the result isn't very pretty to say the least

**Comment by Oxtie** [comment]
I've had bouncy animation on folders (previous iPhones). I think use to look great 😃 then again,.. It can be a matter of preference. Atleast you can give option (improvements may follow In future?😉)

**Comment by Hoangdus** [comment]
I'll see what I can do

**Comment by Oxtie** [comment]
Awesome 🫡 thanks for your efforts and time 😅

**Comment by Hoangdus** [comment]
I did what I can and here is the [result](https://github.com/Hoangdus/Speedster/releases/tag/2.1.0). Hope you enjoy!
