### ISSUE TITLE
In-app-animations doesn’t work in every app

### ISSUE THREAD

**Issue by rasch3n** [Hoangdus/Speedster#5]
I noticed that it just really works in the settings app.

**Comment by gototheskinny** [comment]
Same for me too
iPhone 12 iOS 15.0
XinaA15 1.1.8 rootful version of the tweak.

**Comment by Hoangdus** [comment]
Yea this is a known problem. Unfortunately some app implements transition animations differently so it's impossible to add support for all of them.

**Comment by Hoangdus** [comment]
Compatibility should be better [now](https://github.com/Hoangdus/Speedster/releases/tag/2.1.0)
