### ISSUE TITLE
Screen sleep and screen wake settings intermittently work

### ISSUE THREAD

**Issue by 9021007** [Hoangdus/Speedster#7]
I have the screen sleep and screen wake settings set to the fastest speeds, but they will intermittently switch to the slowest speeds. The sliders do not change position in settings when this happens. 

iOS 16.2
Dopamine
Speedster v2.1.1

**Comment by Hoangdus** [comment]
Have you tried respring twice?

**Comment by 9021007** [comment]
Yes, it is still an issue after respringing twice.

**Comment by 9021007** [comment]
Wait, I was able to fix, I had the slider set incorrectly. I was under the impression that left was faster.
